version: '3.8'

networks:
  network:
    driver: bridge

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: KEYCLOAK
    restart: always
    command: start
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
    ports:
      - "9090:8080"
    networks:
      - network
